FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY pkg ./pkg
COPY resources ./resources

RUN go test -v --skip "_IT" ./...

RUN CGO_ENABLED=0 GOOS=linux go build -o embeddings cmd/embeddings/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/embeddings .

ENTRYPOINT [ "./embeddings" ]
