FROM golang:1.25

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY pkg ./pkg
COPY internal ./internal
COPY resources ./resources
ENTRYPOINT ["go"]
CMD ["test", "-v", "./..."]
