services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434" # Exposes Ollama API on localhost:11434
    volumes:
      - ./ollama:/root/.ollama # Host-mounted directory for models & configs
    restart: unless-stopped
  pgvector:
    build:
      dockerfile: ./psql/postgres.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: secretpassword
      POSTGRES_DB: testdb
    volumes:
      - ./psql/data/postgres:/var/lib/postgresql/data
